### PR TITLE
Exercise 7 & Assignment 1

### PR DESCRIPTION
**Pull request by Jbluni**

### CODE REVIEW

**Comment by kristianolesenlarsen** [comment]
You have made changes in a folder that isn't yours. Can you just revert that change and update the PR?

**Comment by Jbluni** [comment]
I did not do anything with that file, why/ how did I change it? Does it work now, when I delete the file?

**Comment by kristianolesenlarsen** [comment]
You shouldn't delete it - that makes the problem worse :) You need to revert your repository back to the state it was in before that file was changed, and then redo your changes. 

I suggest simply copying your work to somewhere else on your pc, then opening github desktop and reverting to a state from before you began work on the assignment. Then you can add your files back in and push those changes.

[This link](https://help.github.com/en/desktop/contributing-to-projects/reverting-a-commit) migh be useful.

**Comment by kristianolesenlarsen** [comment]
The change happened in [this commit](https://github.com/Kristianuruplarsen/sdseml_online_exercises/pull/127/commits/a12f8ea42c02cf90e80e8788c42904be247e2e12) so reverting back to the one before that should fix the problem.

**Pull request closed without merging**
