### PR TITLE
Create test

### PR DESCRIPTION
**Pull request by vgk616**
test

### CODE REVIEW

**Comment by kristianolesenlarsen** [comment]
Do you want me to merge this? Otherwise i can tell you that everything is working fine.

**Comment by vgk616** [comment]
Hi Kristian,

That was a mistake that I pushed the “test”.

Thank you

BR Christian

Sendt fra min iPhone

Den 20. mar. 2020 kl. 15.38 skrev Kristian Urup Olesen Larsen <notifications@github.com<mailto:notifications@github.com>>:


Do you want me to merge this? Otherwise i can tell you that everything is working fine.

**Comment by vgk616** [comment]
Hi Kristian,


I do not see my contribution to exercise 6 + warmup in your github repository - it should be located in a folder called "Christianhech", where I posted my contribution to exercise 5 last week as well. However, I cannot see the folder anymore, so I was wondering whether I did something wrong. I believe I did the pull request in the correct way.


Have I made a mistake or?


BR Christian Hechmann

________________________________
Fra: Kristian Urup Olesen Larsen <notifications@github.com>
Sendt: 20. marts 2020 19:34:04
Til: Kristianuruplarsen/sdseml_online_exercises
Cc: Christian Hechmann; Author
Emne: Re: [Kristianuruplarsen/sdseml_online_exercises] Create test (#19)


Closed #19<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKristianuruplarsen%2Fsdseml_online_exercises%2Fpull%2F19&data=02%7C01%7Cvgk616%40alumni.ku.dk%7C6c0332b6a844426b226c08d7ccfd450b%7Ca3927f91cda14696af898c9f1ceffa91%7C0%7C0%7C637203260475350049&sdata=A5sY4SLFc34XylYzAe%2F2Szgwy%2FXKPlWEi9E2J31Debw%3D&reserved=0>.

**Comment by kristianolesenlarsen** [comment]
I have never merged a PR from you (this is the only one you have submitted) so your files are not in kristianuruplarsen/sdseml_online_exercises. 

Also there is no folder called "Christianhech" in your version of the repo (here: https://github.com/vgk616/sdseml_online_exercises), so i don't think you have pushed your files to you own fork either.

In case you haven't seen it, there is a guide for using git [here](https://github.com/Kristianuruplarsen/sdseml_online_exercises/blob/master/GITHUB_HOWTO.md).  Let me know if you need any more assistance.

**Pull request closed without merging**
