### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by madselarsen**

### CODE REVIEW

**Comment by kristianolesenlarsen** [comment]
Can you remove .DS_Store from the PR?

If you refork this repo i have updated .gitignore to automatically remove .DS_Store files from commits, in case you dont want to go back and remove it every time you submit a PR.

**Comment by madselarsen** [comment]
Hej Kristian

Jeg fjernede DS_Store og laved en ny pull request, men jeg kan se at min mappe ikke er blevet uploadet til din master. Hvad gør jeg mon forkert?


On 27 Mar 2020, at 14.05, Kristian Urup Olesen Larsen <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you remove .DS_Store from the PR?

If you refork this repo i have updated .gitignore to automatically remove .DS_Store files from commits, in case you dont want to go back and remove it every time you submit a PR.

**Comment by madselarsen** [comment]
Hej igen

Min fejl. De ligger der nu. Jeg må have kigget forkert.

Fortsat god aften…

Mvh Mads Emil

On 27 Mar 2020, at 14.05, Kristian Urup Olesen Larsen <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you remove .DS_Store from the PR?

If you refork this repo i have updated .gitignore to automatically remove .DS_Store files from commits, in case you dont want to go back and remove it every time you submit a PR.

**Comment by kristianolesenlarsen** [comment]
Du skal bare vente på at jeg merger dit PR. Det er gjort nu.

**Pull request closed without merging**
